name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Formatter
        run: deno fmt --check

      - name: Linter
        run: deno lint --unstable

  check:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Type check
        run: deno run --unstable mod.ts
